#! /usr/bin/env php
<?php
	require_once('nimblize/nimblize.php');
	require_once('nimblize/nimble_generators/lib/generator.php');
	define('NIMBLE_ROOT', dirname(__FILE__) . DIRECTORY_SEPARATOR . '..');
	Generator::$nimble_root = NIMBLE_ROOT;
	
	if(count($argv) < 2) {
		echo NIMBLE_ROOT;
		echo Generator::help();
		exit(1);
	}
	
	switch($argv[1]) {	
		case 'controller':
			Generator::controller(Inflector::classify($argv[2]));
		break;		
		
		case 'model':
		  $parent = isset($argv[3]) ? $argv[3] : '';
			Generator::model($argv[2], $parent);
			Generator::migration($argv[2], Inflector::tableize($argv[2]));
		break;		
		
		case 'test':
			if(!isset($argv[3])) {
				echo "Please supply a test name.\n";
				exit(1);
			}
			Generator::generate_test($argv[2], $argv[3]);
  	break;
  	
		case 'help':
			echo Generator::help();
		break;
		
		case 'mailer':
			$new = $argv;
			$methods = array_splice($new, 3);
		 	$methods = empty($methods) ? array('foo') : $methods;
			Generator::mailer($argv[2], $methods);
		break;
		
		case 'migration':
			Generator::migration($argv[2]);
  	break;
	}
?>